# Generated by Django 3.1.3 on 2020-11-12 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=500)),
                ('nombres', models.CharField(max_length=500)),
                ('apellidos', models.CharField(max_length=500)),
                ('direccion', models.CharField(max_length=500)),
                ('ciudad', models.CharField(max_length=500)),
                ('nrocontacto', models.IntegerField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Cortinas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancho', models.IntegerField(max_length=500)),
                ('alto', models.IntegerField(max_length=500)),
                ('rut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
            ],
        ),
    ]
