# Generated by Django 3.1.3 on 2020-11-22 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201121_2253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cortinas',
            old_name='fecha',
            new_name='direccion',
        ),
    ]
