# Generated by Django 3.1.3 on 2020-11-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201121_2257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('correo', models.CharField(max_length=500)),
                ('mensaje', models.CharField(max_length=2000)),
            ],
        ),
    ]
