# Generated by Django 3.1.3 on 2020-11-25 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cortinas',
            name='imagen',
            field=models.ImageField(null=True, upload_to=None),
        ),
    ]
