# Generated by Django 3.1.3 on 2020-11-30 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_cortinas_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cortinas',
            name='imagen',
            field=models.ImageField(null=True, upload_to='core/img'),
        ),
    ]
