# Generated by Django 4.1.5 on 2023-01-23 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201129_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('stock', models.IntegerField()),
                ('codigo_barra', models.IntegerField()),
                ('direccion', models.CharField(max_length=500)),
                ('numerotelefono', models.IntegerField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='')),
                ('reserva', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudReserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreSolicitante', models.CharField(max_length=100)),
                ('rut', models.IntegerField(unique=True)),
                ('telefono', models.CharField(max_length=100)),
                ('asignatura', models.CharField(max_length=100)),
                ('carrera', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('fecha_salida', models.DateField()),
                ('fecha_entrega', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Contacto',
        ),
        migrations.DeleteModel(
            name='Cortinas',
        ),
    ]
