# Generated by Django 3.1.2 on 2023-01-24 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_solicitudreserva_fecha_entrega_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudreserva',
            name='estadoreserva',
            field=models.BooleanField(default=False, verbose_name='ESTADO PENDIENTE'),
        ),
    ]
