# Generated by Django 4.1.5 on 2023-01-27 16:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20230124_1200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulos',
            old_name='direccion',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='articulos',
            old_name='nombre',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='articulos',
            old_name='reserva',
            new_name='estado_articulo',
        ),
        migrations.RenameField(
            model_name='articulos',
            old_name='numerotelefono',
            new_name='stock_sede',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='apellidos',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='solicitudreserva',
            old_name='nombreSolicitante',
            new_name='codigo_equipo',
        ),
        migrations.RenameField(
            model_name='solicitudreserva',
            old_name='estadoreserva',
            new_name='estado_reserva',
        ),
        migrations.RenameField(
            model_name='solicitudreserva',
            old_name='fecha_entrega',
            new_name='fecha',
        ),
        migrations.RemoveField(
            model_name='articulos',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='articulos',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nombres',
        ),
        migrations.AddField(
            model_name='articulos',
            name='fecha_ingreso',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articulos',
            name='nombre_articulo',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articulos',
            name='observaciones',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articulos',
            name='persona_prestamo',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitudreserva',
            name='cantidad_solicitada',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitudreserva',
            name='fecha_llegada',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='solicitudreserva',
            name='nombre',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitudreserva',
            name='nombre_equipo',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitudreserva',
            name='profesor',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicitudreserva',
            name='rut',
            field=models.CharField(max_length=10),
        ),
    ]
