# Generated by Django 3.1.2 on 2023-02-27 06:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_articulos_fecha_ingreso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='fecha_ingreso',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 27, 6, 2, 54, 305479)),
        ),
        migrations.AlterField(
            model_name='solicitudreserva',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 27, 6, 2, 54, 305479)),
        ),
        migrations.AlterField(
            model_name='solicitudreserva',
            name='fecha_salida',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 27, 6, 2, 54, 305479)),
        ),
    ]
