# Generated by Django 3.1.2 on 2024-09-27 14:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20230227_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='estado',
            field=models.CharField(max_length=500, verbose_name='Estado del Articulo'),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='estado_articulo',
            field=models.BooleanField(verbose_name='Disponibilidad del Articulo'),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='fecha_ingreso',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 27, 14, 48, 14, 857348)),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='persona_prestamo',
            field=models.CharField(max_length=500, verbose_name='Creador articulo'),
        ),
        migrations.AlterField(
            model_name='solicitudreserva',
            name='estado_reserva',
            field=models.BooleanField(default=False, verbose_name='APROBAR SOLICITUD'),
        ),
        migrations.AlterField(
            model_name='solicitudreserva',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 27, 14, 48, 14, 857348)),
        ),
        migrations.AlterField(
            model_name='solicitudreserva',
            name='fecha_salida',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 27, 14, 48, 14, 857348)),
        ),
    ]
